In [1]:
import numpy as np #creating a numpy array
l1=[1, 2, 3, 4, 5]

n1=np.array(l1)

n1

array([1, 2, 3, 4, 5])

In [2]:
type(n1) #definig the type of our array

numpy.ndarray

In [3]:
l2=([1, 2, 3], [3, 2, 1]) #array with 2 coloumns

n2=np.array(l2)

n2

array([[1, 2, 3],
       [3, 2, 1]])

In [4]:
type(n2) #defining the type of above mentioned array

numpy.ndarray

In [5]:
import numpy as np  #displaying elements of array with zeros 
n3 = np.zeros((1,2))
n3

array([[0., 0.]])

In [6]:
type(n3) #defining the type of above mentioned array

numpy.ndarray

In [11]:
n4=np.zeros((10,10)) #displaying elements of 10x10 array with zeros 
n4



array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
n5=np.full((5,5),2) #creating a 5x5 array with 2
n5

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [20]:
n6=np.arange(1, 1000) #printing all elements between 1 to 1000 using "np.arange"
n6

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [31]:
n7=np.arange(1, 5000, 5) #printing all elements bt 1 to 5000 with the differnece of 5
n7

array([   1,    6,   11,   16,   21,   26,   31,   36,   41,   46,   51,
         56,   61,   66,   71,   76,   81,   86,   91,   96,  101,  106,
        111,  116,  121,  126,  131,  136,  141,  146,  151,  156,  161,
        166,  171,  176,  181,  186,  191,  196,  201,  206,  211,  216,
        221,  226,  231,  236,  241,  246,  251,  256,  261,  266,  271,
        276,  281,  286,  291,  296,  301,  306,  311,  316,  321,  326,
        331,  336,  341,  346,  351,  356,  361,  366,  371,  376,  381,
        386,  391,  396,  401,  406,  411,  416,  421,  426,  431,  436,
        441,  446,  451,  456,  461,  466,  471,  476,  481,  486,  491,
        496,  501,  506,  511,  516,  521,  526,  531,  536,  541,  546,
        551,  556,  561,  566,  571,  576,  581,  586,  591,  596,  601,
        606,  611,  616,  621,  626,  631,  636,  641,  646,  651,  656,
        661,  666,  671,  676,  681,  686,  691,  696,  701,  706,  711,
        716,  721,  726,  731,  736,  741,  746,  7

In [42]:
n8=np.random.randint(1, 70, 7) #printing a random integer from given array
n8

array([18, 42, 21, 42, 36, 41,  7])

In [54]:
n9=np.array(([1,2,3],[3, 2, 1])) #printing the shape in terms of rows and columns

n9.shape

(2, 3)

In [58]:
n9.shape=(3, 2)
n9.shape

(3, 2)

In [64]:
n10=np.array([1,2,3]) #changing the shape of array
n11=np.array([4,5,6])
np.column_stack((n10,n11))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [65]:
np.hstack((n10,n11)) #horizontal stack

array([1, 2, 3, 4, 5, 6])

In [63]:
np.vstack((n10,n11)) #vertical stack

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
import numpy as np #printing common elements
n12=np.array([10, 20, 30, 40, 50, 60])
n13=np.array([50, 60, 70, 80, 90])
np.intersect1d(n12, n13)

array([50, 60])

In [13]:
n12=np.array([10, 20, 30, 40, 50, 60]) #printing out ucommon elents of first array
n13=np.array([50, 60, 70, 80, 90])
np.setdiff1d(n12, n13)

array([10, 20, 30, 40])

In [15]:
n14=np.array([34, 78]) #adding all elements of both arrays
n15=np.array([65, 97])
np.sum([n14, n15])

274

In [28]:
#adding elements column wise
np.sum([n14, n15],axis=0)

array([ 99, 175])

In [30]:
np.sum([n14, n15],axis=1) #adding elements row wise

array([112, 162])

In [32]:
n16=np.array([1, 2, 3, 4, 5]) #basic addition 
n17=n16+3
n17

array([4, 5, 6, 7, 8])

In [34]:
n18 = n16*5
n18

array([ 5, 10, 15, 20, 25])

In [35]:
n19 = n16/3
n19

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [39]:
n7=np.arange(1, 5000, 5)
n7


array([   1,    6,   11,   16,   21,   26,   31,   36,   41,   46,   51,
         56,   61,   66,   71,   76,   81,   86,   91,   96,  101,  106,
        111,  116,  121,  126,  131,  136,  141,  146,  151,  156,  161,
        166,  171,  176,  181,  186,  191,  196,  201,  206,  211,  216,
        221,  226,  231,  236,  241,  246,  251,  256,  261,  266,  271,
        276,  281,  286,  291,  296,  301,  306,  311,  316,  321,  326,
        331,  336,  341,  346,  351,  356,  361,  366,  371,  376,  381,
        386,  391,  396,  401,  406,  411,  416,  421,  426,  431,  436,
        441,  446,  451,  456,  461,  466,  471,  476,  481,  486,  491,
        496,  501,  506,  511,  516,  521,  526,  531,  536,  541,  546,
        551,  556,  561,  566,  571,  576,  581,  586,  591,  596,  601,
        606,  611,  616,  621,  626,  631,  636,  641,  646,  651,  656,
        661,  666,  671,  676,  681,  686,  691,  696,  701,  706,  711,
        716,  721,  726,  731,  736,  741,  746,  7

In [40]:
np.mean(n7) #finding mean of given data

2498.5

In [41]:
np.median(n7) #finding meadian of given data 

2498.5

In [42]:
np.std(n7) #finding standard deviation of given data 

1443.3749512860475

In [44]:
n18=np.array([1, 2, 3, 4, 5]) #saving a array
np.save("my array", n18)

In [45]:
new = np.load("my array.npy") #loading a array
new

array([1, 2, 3, 4, 5])